version: '3'
services:

  app:
    build: .

    ports:
      - "8080:8080"
    restart: always

    depends_on:
      - mysql
    privileged: true

  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./backend/data/db/mysql:/var/lib/mysql
      - ./backend/data/db/initdb.d:/docker-entrypoint-initdb.d
      - ./backend/data/db/sql:/sql
    environment:
      MYSQL_DATABASE: "corporeity"
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"