app:
  name: "webApp"
  mode: "release"
  port: 8080
  machine-id: 1

mysql:
  host: mysql
  port: 3306
  password: "123456"
  user: root
  dbname: "corporeity"

log:
  level: "debug"
  filename: "./backend/webApp.log"
  max_size: 200
  max_age: 30
  max_backups: 7
