app:
  name: "webApp"
  mode: "release"
  port: 8081
  machine-id: 1

mysql:
  host: "127.0.0.1"
  port: 3306
  password: "000000"
  user: root
  dbname: "corporeity"

log:
  level: "debug"
  filename: "./backend/webApp.log"
  max_size: 200
  max_age: 30
  max_backups: 7
