// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es/el-aside')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCol: typeof import('element-plus/es/el-col')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElHeader: typeof import('element-plus/es/el-header')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElMain: typeof import('element-plus/es/el-main')['default']
    ElMenu: typeof import('element-plus/es/el-menu')['default']
    ElMenuItem: typeof import('element-plus/es/el-menu-item')['default']
    ElMenuItemGroup: typeof import('element-plus/es/el-menu-item-group')['default']
    ElRow: typeof import('element-plus/es/el-row')['default']
    ElSubmenu: typeof import('element-plus/es/el-submenu')['default']
    ElTable: typeof import('element-plus/es/el-table')['default']
    ElTableColumn: typeof import('element-plus/es/el-table-column')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
